### PR TITLE
Color variables and story

### PR DESCRIPTION
**Pull request by ArielDKenan**

### CODE REVIEW

**Comment by ArielDKenan** [comment]
Are the color class mixins used anywere besides component lab story for colors? If not, they should probably be moved to component lab scss file.

**Comment by einavk** [comment]
Ariel, are you sure this is the latest color set? 
@michalweinsh can you please verify? go to ariel's github page pls

**Comment by michalweinsh** [comment]
@einavk i have a pdf they send but i don't think it was updated on TDP

**Review by einavk — APPROVED** [review]
checked against style guide file

**Pull request merged**
