### PR TITLE
Drop down patch2

### PR DESCRIPTION
**Pull request by Idanmsbit**
Changed the way drop-down animatio works

### CODE REVIEW

**Comment by ArielDKenan** [comment]
Hi Idan

Don't ever use 'transition: all'. It can cause serious performance issues
and unwanted behavior. Just specify the property names you want to animate
and set the properties for each of them.

Even trying to override the 'transition: all' side effects by using a
subsequent 'transition-property-name: x, y' would only override the
property types that are styled by other transition properties (like
transition-duration). Other properties not intended for animation will
still be affected by the original declaration of transition: all.

There is a bug with your dropdown animation, in which the overflow causes
an unwanted scrollbar during the expand animation. This can be fixed by
using Keyframes to set overflow to hidden at the start of the transition,
and with a delay that will set overflow-y back to auto after the transition
completes.

Also be sure to remove all commented code.

Hope that was helpful


On Dec 20, 2017 5:24 PM, "Idan Baraness" <notifications@github.com> wrote:

Changed the way drop-down animatio works
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/onap-sdc/sdc-ui/pull/220
Commit Summary

   - Changed dropdown animation names to animation-fold/animation-expend.
   I'll be using animation prefix for every new animation
   - Changed dropdown animation names to 'transition-vertical-collapse' and
   'transition-vertical-expand'
   - Merge branch 'animation-styles' of https://github.com/ibaraness/sdc-ui
   into animation-styles
   - Changed dropdown animation names to 'transition-vertical-collapse' and
   'transition-vertical-expand', and removed scroll-bar showing during
   animation.
   - Animation types was changed
   - Animation type for drop-down was changed

File Changes

   - *M* components/dropdown/_dropdown.scss
   <https://github.com/onap-sdc/sdc-ui/pull/220/files#diff-0> (44)
   - *M* scss/common/_animation.scss
   <https://github.com/onap-sdc/sdc-ui/pull/220/files#diff-1> (64)
   - *M* src/angular/form-elements/dropdown/dropdown.component.html
   <https://github.com/onap-sdc/sdc-ui/pull/220/files#diff-2> (41)
   - *M* src/angular/form-elements/dropdown/dropdown.component.ts
   <https://github.com/onap-sdc/sdc-ui/pull/220/files#diff-3> (5)
   - *M* stories/ng2-component-lab/dropdown.component.exp.ts
   <https://github.com/onap-sdc/sdc-ui/pull/220/files#diff-4> (20)

Patch Links:

   - https://github.com/onap-sdc/sdc-ui/pull/220.patch
   - https://github.com/onap-sdc/sdc-ui/pull/220.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/onap-sdc/sdc-ui/pull/220>, or mute the thread

**Comment by ibaraness** [comment]
Hi Ariel,

I imagine it's not very hatd to say please, and there was a reason I was
using transition all. About the doc comments I would solve it with the
scrum master as I've been told

בתאריך 20 בדצמ׳ 2017 8:59 אחה״צ,‏ "Ariel Kenan" <notifications@github.com>
כתב:

> Hi Idan
>
> Don't ever use 'transition: all'. It can cause serious performance issues
> and unwanted behavior. Just specify the property names you want to animate
> and set the properties for each of them.
>
> Even trying to override the 'transition: all' side effects by using a
> subsequent 'transition-property-name: x, y' would only override the
> property types that are styled by other transition properties (like
> transition-duration). Other properties not intended for animation will
> still be affected by the original declaration of transition: all.
>
> There is a bug with your dropdown animation, in which the overflow causes
> an unwanted scrollbar during the expand animation. This can be fixed by
> using Keyframes to set overflow to hidden at the start of the transition,
> and with a delay that will set overflow-y back to auto after the transition
> completes.
>
> Also be sure to remove all commented code.
>
> Hope that was helpful
>
>

**Comment by ArielDKenan** [comment]
Hi Idan,

I didn't mean to offend anyone. I am just trying to work together. I'd like to work with you on this, maybe we could communicate by phone? Israel, Eli and Leib have my number. I am working on the React implementation of the dropdown and I would like everyone to be on the same side.

**Review by islavi — APPROVED** [review]
@ArielDKenan please look at this and add your fixes.

**Review by islavi — APPROVED** [review]
@ArielDKenan need to continue

**Comment by ArielDKenan** [comment]
Nice work Idan

**Pull request merged**
