### PR TITLE
Feature/fix tiles patch2

### PR DESCRIPTION
**Pull request by islavi**

### CODE REVIEW

**Review by ArielDKenan — APPROVED** [review]
Looks good. Nice idea with the 'childs' folder. Maybe consider renaming it to 'children', it's the correct plural of 'child'

**Comment by ArielDKenan** [comment]
I just checked your github pages and noticed the :last-child on tile-info-line is never triggering. A nice solution might be to remove 'margin-bottom: -4px' from .tile-content, instead of using the :last-child.

**Comment by islavi** [comment]
Thanks Ariel,
I removed the margin-bottom: -4px, we should not use minus in margin and padding.
The  :last-child is to add gap of 4px from the bottom. It works for me, see if it is some caching issue.
I will change folder name to "children".

**Comment by ArielDKenan** [comment]
Yes, I see it working now. Looks good

**Pull request merged**
