### PR TITLE
Typography

### PR DESCRIPTION
**Pull request by ilanap**
using downloaded font familes

### CODE REVIEW

**Comment by einavk** [comment]
Hi,
Please remove the comments and I'll approve

**Review by ArielDKenan — COMMENTED** [review]
Add support for woff1 (.woff) on the fonts. For example change the src properties to this structure:
src: url(....woff2) format("woff2"), url(....woff) format("woff");

**Comment by ArielDKenan** [comment]
Also we need to check the latest typography style guide. If it has italic, we need to add a font-face for OpenSans-Italic. If not, we need to remove the body-1-italic mixin.

**Comment by ilanap** [comment]
There is no woff version of the font, only woff2. this is only for the github pages, in the sdc-ui implementations, the font is loaded through the application and from a different url/format if needed but with the same name.

**Comment by ArielDKenan** [comment]
Here are the links for the fonts in .woff:
@font-face {
  src: local('Open Sans Regular'), local('OpenSans-Regular'), url(http://fonts.gstatic.com/s/opensans/v15/cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff) format('woff');
}

@font-face {
  src: local('Open Sans SemiBold'), local('OpenSans-SemiBold'), url(http://fonts.gstatic.com/s/opensans/v15/MTP_ySUJH_bn48VBG8sNSnhCUOGz7vYGh680lGh-uXM.woff) format('woff');
}

@font-face {
  src: local('Open Sans Italic'), local('OpenSans-Italic'), url(http://fonts.gstatic.com/s/opensans/v15/xjAJXh38I15wypJXxuGMBobN6UDyHWBl620a-IRfuBk.woff) format('woff');
}


And the italic in .woff2:
@font-face {
  src: local('Open Sans Italic'), local('OpenSans-Italic'), url(http://fonts.gstatic.com/s/opensans/v15/xjAJXh38I15wypJXxuGMBo4P5ICox8Kq3LLUNMylGO4.woff2) format('woff2');
}

**Comment by ArielDKenan** [comment]
If we want Vietnamese in italic:
/* vietnamese */
@font-face {
  font-family: 'Open Sans';
  font-style: italic;
  font-weight: 400;
  src: local('Open Sans Italic'), local('OpenSans-Italic'), url(http://fonts.gstatic.com/s/opensans/v15/xjAJXh38I15wypJXxuGMBr6up8jxqWt8HVA3mDhkV_0.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+1EA0-1EF9, U+20AB;
}

**Review by ArielDKenan — APPROVED** [review]

**Pull request merged**
