### PR TITLE
Changing font sizes for tiles.

### PR DESCRIPTION
**Pull request by islavi**
Changing font sizes for tiles.
@lizronen @michalweinsh

### CODE REVIEW

**Comment by michalweinsh** [comment]
@islavi @lizronen Is there a reason you reduced the font size? Liz and I decided about specific sizes.

**Comment by ArielDKenan** [comment]
Style changes need to be approved by our designers, as we are using sdc-ui all across our app.

**Comment by islavi** [comment]
@ArielDKenan do not close pull request without getting approve from us!

**Comment by ArielDKenan** [comment]
Well you weren't responding to the question posted on the pull request, and
Michal informed me it was agreed with your team that the code should not be
pushed.

Its also just 3 lines of code. Why do you want it open?

**Comment by einavk** [comment]
Hi @islavi ,
Following the restyling of all tiles in #107 the same change was introduced, so I'm closing this pull request.
Thanks

**Pull request closed without merging**
