### PR TITLE
Feature/new buttons

### PR DESCRIPTION
**Pull request by ArielDKenan**
-Created additional parameter for button: default/outline
-Created styling rules for each button type, both for default and outline
-Added new colors to variables.scss per latest button designs
-Added new prop to ReactButton to determine default or outline
-Added storybook examples for every type of button in HTML & React
-Updated button spec to test for all buttons

### CODE REVIEW

**Review by nomrik — COMMENTED** [review]
Has this been reviewd by @michalweinsh ?

If not, michal - check out https://arieldkenan.github.io/sdc-ui

**Comment by michalweinsh** [comment]
@nomrik i don't have access to https://arieldkenan.github.io
viewing the buttons on http://arielke01:6006

**Comment by nomrik** [comment]
@michalweinsh sorry, wrote the wrong link. fixed it now. It's preferred to review on the online env and not the local one.. more reliable

**Comment by ArielDKenan** [comment]
They are the same thing right now

On May 17, 2017 1:14 PM, "Michal Weinstein" <notifications@github.com>
wrote:

@nomrik <https://github.com/nomrik> i don't have access to
https://arieldkenan.github.io
viewing the buttons on http://arielke01:6006

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/onap-sdc/sdc-ui/pull/46#issuecomment-302047830>, or mute
the thread

**Comment by nomrik** [comment]
Yeah I know, just to get used to it. I mean you could have changed something on your local env without thinking about Michal using it.. Better to keep it seperated

**Pull request closed without merging**
