### PR TITLE
Tiles

### PR DESCRIPTION
**Pull request by RachelCohen1**

### CODE REVIEW

**Review by islavi — CHANGES_REQUESTED** [review]
Regarding the tiles, you did not understand what I meant.
I do not want it to be exactly like Amdocs.
I want it to be like this:
```
<sdc-tile>
                <sdc-tile-header>
<div class="blue" ng-reflect-ng-class="blue">P</div>
</sdc-tile-header>
                <sdc-tile-info>
<div class="sdc-tile-content-icon blue">some icon …</div>
                                <div class="sdc-tile-content-info">
    <span class="sdc-tile-info-line title">Router</span>
    <div class="sdc-tile-info-line supertitle">test</div>
</div>
</sdc-tile-info>
                <sdc-tile-footer>
                                <span class="sdc-tile-footer-cell"> Footer </span>
</sdc-tile-footer>
</sdc-tile>
```
So user can change the content inside the way he wants.
The above can be in the examples.
I do not want to create component for each line (performance issues), instead we can use div/span with the class (style) needed.
Later we can create specific component, that will wrap this component and only get inputs (but I do not want this for now). 

Also please verify if there are conflicts, after you do pull request.
Enter to onap/sdc-ui and press on pull request and see if there are conflicts.

**Comment by RachelCohen1** [comment]
Check if that's what you mean.
(It seems I don't have permissions to merge the code.)

2017-12-07 17:38 GMT+02:00 Israel <notifications@github.com>:

**Comment by ArielDKenan** [comment]
It's important to understand how the tile-info-line classes are meant to be used. They go in the following order (for up to 3 lines):
.supertitle
.title
.subtitle
The is meant to be above the title (as the name implies) and the subtitle to be below the title. The use of the info lines should follow this and the tiles should be made to look like the design using this order.

**Review by islavi — APPROVED** [review]

**Review by islavi — COMMENTED** [review]
N/A

**Pull request merged**
