### PR TITLE
Bug/tile

### PR DESCRIPTION
**Pull request by fridmaster**
fixed some css issues

### CODE REVIEW

**Comment by einavk** [comment]
Question:

Why did you change the display for sdc-tile-content-info to be inline-block instead of flex ?

**Comment by fridmaster** [comment]
@einavk 

[display for tile info line css class is flex where it should be inline-block.](https://github.com/onap-sdc/sdc-ui/issues/172)

You opened a bug about it. I fixed it - like you told and checked that it works.

**Comment by einavk** [comment]
my bug was opened for .sdc-tile-info-line not for .sdc-tile-content-info...
And in any case, if .sdc-tile-content-info was supposed to be inline-block (which it does not), then you would need to remove the flex-direction as it makes no sense to have them both.

**Comment by fridmaster** [comment]
@einavk Sorry for that issue. I added some changes which related to new requirements and fixed display value.

**Comment by ArielDKenan** [comment]
To this code: $tile-width-less-padding: $tile-full-width - ($tile-padding * 2)
You added: - ($border-width * 2)
The tile has property box-sizing: border-box (see the line "@include box-sizing;"), which means you do not need to subtract the border size to get the actual width. Box-sizing: border-box includes margin, padding, and border in calculating width.

To do this you added "$border-width: 1px;" There is absolutely no need to store the border size in a variable, especially now that you are removing the inclusion of border-width in the tile-width calculation.

**Comment by ArielDKenan** [comment]
The tile-info-line classes are meant to be used in a specific order:
.supertitle
.title
.subtitle
The supertitle goes above the title (hence the name), the title is the main text, and the subtitle goes below the title (hence the name). Recent changes made broke the style regarding this, though it looks fine in your examples because .supertitle is used below .title. A line below a title needs to have the class .subtitle, and we need to make sure that the tiles look good when the info-lines are given classes with the proper order.

**Comment by fridmaster** [comment]
Thank you@ArielDKenan I will fix this issue.
Do I  need to fix margin issues and flow or something else? Does Ellipsis work now as you want?
In this design there is no super-Title at all.  
https://github.com/onap-sdc/sdc-ui/issues/177

**Review by islavi — APPROVED** [review]

**Pull request merged**
